name: "Post release"
on:
  release:
    types:
      - published

env:
  GO_VERSION: '1.26'

jobs:
  update-assets:
    name: "Update reference assets"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Update reference files
        run: cp .golangci.next.reference.yml .golangci.reference.yml

      - name: Update JSON schema files
        run: cp jsonschema/golangci.next.jsonschema.json jsonschema/golangci.jsonschema.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: timestamp
          title: "chore: update reference assets after release"
          delete-branch: true
          body: |
            - [ ] update changelog
            - [ ] add previous version JSON schema

  check-install-script:
    name: Installation script (remote)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Check installation script
        run: cat ./install.sh | sh -s -- -b "./install-gopherlint"
