name: Checks
on:
  push:
    branches:
      - main
  pull_request:

env:
  # https://github.com/actions/setup-go#supported-version-syntax
  # ex:
  # - 1.18beta1 -> 1.18.0-beta.1
  # - 1.18rc1 -> 1.18.0-rc.1
  GO_VERSION: '1.26'

jobs:
  # Check if there is any dirty change for go mod tidy
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

  check-local-install-script:
    name: Installation script (local)
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Check installation script
        run: cat ./install.sh | sh -s -- -d -b "./install-gopherlint"

  # Note: the command `run` is tested by the other workflows (`make test`).
  check-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build gopherlint
        run: make build

      - run: ./gopherlint

      - run: ./gopherlint fmt
      - run: ./gopherlint fmt --diff
      - run: cat cmd/gopherlint/main.go | ./gopherlint fmt --stdin

      - run: ./gopherlint cache
      - run: ./gopherlint cache status
      - run: ./gopherlint cache clean

      - run: ./gopherlint completion
      - run: ./gopherlint completion bash
      - run: ./gopherlint completion bash --no-descriptions
      - run: ./gopherlint completion zsh
      - run: ./gopherlint completion zsh --no-descriptions
      - run: ./gopherlint completion fish
      - run: ./gopherlint completion fish --no-descriptions
      - run: ./gopherlint completion powershell
      - run: ./gopherlint completion powershell --no-descriptions

      - run: ./gopherlint config
      - run: ./gopherlint config path
      - run: ./gopherlint config path --json
      - run: ./gopherlint config verify --schema jsonschema/golangci.next.jsonschema.json

      - run: ./gopherlint help
      - run: ./gopherlint help linters
      - run: ./gopherlint help linters --json
      - run: ./gopherlint help formatters
      - run: ./gopherlint help formatters --json
      - run: ./gopherlint linters
      - run: ./gopherlint linters --json
      - run: ./gopherlint formatters
      - run: ./gopherlint formatters --json
      - run: ./gopherlint version
      - run: ./gopherlint version --short
      - run: ./gopherlint version --debug
      - run: ./gopherlint version --json
      - run: ./gopherlint version --json --debug
